- packages/debian/postinst
- Changed the idtype to module to align with AIS expectations
This means that AIS will attempt to provision an ADU module unless the user changes the generated principal for ADU located in the adu.toml.
> Changed  idtype to default to module to align with AIS expectations

- azurepipelines/adu-debian-arm32-build.yml
- azurepipelines/adu-ubuntu-arm64-build.yml
- scripts/install-deps.sh
Now that all pipelines are green, we disable ARM 32 Debian9 and Ubuntu ARM 64 builds during daily development.
There is on-going work to improvement the build time of these two builds & refactor the yaml files, whose priority is dependent on the ask from PM of supporting these two arches
* Note: There is a mistake from previous PR on `install-deps.sh`, I added the fix in this PR.
> Task 31853332: Disable ARM 32 Debian9 and Ubuntu ARM 64 builds.

- src/content_handlers/apt_handler/inc/aduc/apt_parser.hpp
- src/content_handlers/apt_handler/src/apt_handler.cpp
- src/content_handlers/apt_handler/src/apt_parser.cpp
- src/content_handlers/apt_handler/tests/apt_parser_ut.cpp
- src/content_handlers/apt_handler/tests/sample_apt_manifest.json
This changes fix **Bug 32158196**: DU Agent doesn't restart after self-update completed.
This is a regression caused by package name changed from "adu-agent" to "deviceupdate-agent".
Currently, the agent automatically restarts during 'apply' if one of the APT package names starts with "adu-agent". This logic is no longer valid. 
- Add 'agentRestartRequired' property to APT Manifest
- Update APT manifest parser to support the new property
- Add more APT update handler unit tests
> Support agentRestartRequired property in APT Manifest

- CMakeLists.txt
- azurepipelines/adu-debian-arm32-build.yml
- azurepipelines/adu-ubuntu-amd64-build.yml
- azurepipelines/adu-ubuntu-arm64-build.yml
changed major, minor, patch, and pre-release versions.
Please ignore the "rc4" in the branch name. It is actually rc1. PR name reflects that.
> Changed version from 0.6.0-public-preview to 0.7.0-rc1-public-preview

- src/agent/adu_core_interface/tests/adu_core_json_ut.cpp
Remove alias or name in the codebase
> Bug 29766090: Remove internal alias from adu_core_json_ut.cpp

- packages/CMakeLists.txt
1. remove libcpprest as an ADUC dependency (libcpprest is a DO dependency)
> Bug 31760435: deviceupdate-agent package failed to install because libcpprest (deliveryoptimization-agent package dependency) wasn't installed

- src/agent/device_info_interface/src/device_info_interface.c
Aligning with this change ADU-M's fix: Bug 32192452: Relax compat info DeviceManufacturer and DeviceModel restrictions
~~**Pending:** Leo is still waiting to hear back from IoT team on the length restrictions here:~~
~~Restrictions on device Manufacturer and model? · Issue #153 · Azure/iot-plugandplay-models (github.com)~~
Confirmed: The length limit remains 64
> Bug 32367663: Relax special chars restrictions on DeviceInfo

- tools/AduCmdlets/create-adu-import-manifest.sh
ADU supposedly accepts ISO 8601 datetime format, but there is a bug in import processing that incorrectly treats offset format as invalid: `2021-04-27T20:56:15+00:00`. Temporarily working around it by using Z designator format: `2021-04-27T20:56:15Z`.
> Fix import manifest creator bash script datetime format

- src/agent/adu_core_interface/inc/aduc/adu_core_export_helpers.h
- src/agent/adu_core_interface/src/adu_core_export_helpers.c
- src/agent/adu_core_interface/src/agent_workflow.c
- src/agent/adu_core_interface/tests/adu_core_export_helpers_ut.cpp
- src/agent/adu_core_interface/tests/adu_core_interface_ut.cpp
When the previous action is Download, and then the device lost connection, when it gets connected and starts up again - it is stuck at `at progress` because the agent reports `idle` in this case, while it should resume the Download workflow.
Add the logic to resume Download workflow as Nox suggested. 
Validation to ensure that this won’t regress anything is needed.
> Bug 32212559: Deployment stuck at ‘in progress’: bug in startup code path

- tools/AduCmdlets/create-adu-import-manifest.sh
This reverts commit 5c07edbb8ef5855f0c156f0c2e2b557b1f7ad0bc.
Server side bug has been fixed and deployed, so undoing the script workaround.
> Revert "datetime fix (#54)"

- packages/debian/postinst
Added the code in our postisnt script to add adu to the do group so we have permissions to write the connection_string to DO in order to fix an issue with the Nested Edge scenario.
> Fixed DO group permissions to allow for writing the connection string

- azurepipelines/adu-debian-arm32-build.yml
- azurepipelines/adu-ubuntu-amd64-build.yml
- azurepipelines/adu-ubuntu-arm64-build.yml
* Migrate from selfhost build to 1es hosted build
* Refactor the ARM builds. Start using Azcontainer to host a container with dependencies installed.
* Stop building debian 9 arm32 until request confirmed from PM.
* Will be merged to release080rc1 branch and later merge to main.
> Task 34732610: (agent build) Pipeline Migration to 1ES

- src/platform_layers/linux_platform_layer/src/linux_adu_core_impl.hpp
Disabling the component changed detection feature.
We're working on the better design that will be available in the next release.
> Disable component changed detection

- src/agent/adu_core_interface/src/adu_core_interface.c
Found this bad boy. 
There might still be other memory leaks still lurking around tho. I keep losing memory when I manually retry a failed device update.
> Fix memory leak in GetReportingJsonValue() - free root JSON_Value when done

- src/content_handlers/simulator_handler/tests/simulator_handler_unit_tests.cpp
**Note:** Update manifest version 4 doesn't contain installedCriteria at the root level.
> Fix simulator handler unit test failure

- packages/debian/postrm
* fix adu-shell postrm failed-upgrade healthcheck for 0.8.0 to 0.8.x upgrade
* add comment on the octal permission bits
> fix postrm failed-upgrade healthcheck, 0.8.0 to 0.8.x (#515)

- src/adu_workflow/src/agent_workflow.c
- src/agent/adu_core_interface/tests/workflow_reboot_ut.cpp
- src/content_handlers/steps_handler/src/steps_handler.cpp
With the new Steps Handler design, Content Handles are responsible for requesting system reboot or agent restart using                 **workflow_request_immediate_agent_restart**, **workflow_request_agent_restart**, **workflow_request_immediate_reboot**, **workflow_request_reboot** APIs.
The state machine must check those requests and perform reboot or restart accordingly.
Changes:
- Update state machine logics
- Fix related unit tests
> Fix regression in reboot and restart logics

- src/content_handlers/script_handler/src/script_handler.cpp
[ADO Bug 39511245](https://microsoft.visualstudio.com/OS/_workitems/edit/39511245): Script Handler return false-positive value when ADUC_LaunchChildProcess exit code != 0, and previous aduc_result file exists
> Fix false-positive result from script handler when child process failed, and previous result file exists.

- src/adu_workflow/src/agent_workflow.c
…ent workflow (#601)
* Cleanup current workflow sandbox before processing deferred, replacement workflow
* remove skipped trace and clang format
* free workflowId and workFolder strings and shorten log trace
> Clean current sandbox before process deferred, replacement workflow

- licenses/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
> Add `$schema` to `cgmanifest.json`

- src/agent/adu_core_interface/src/adu_core_interface.c
- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
- src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
- src/utils/d2c_messaging/inc/aduc/d2c_messaging.h
- src/utils/d2c_messaging/src/d2c_messaging.c
- src/utils/workflow_utils/src/workflow_utils.c
- Fix an issue for image-based update scenario where the device doesn't reboot after the new image is installed.
- Add ADUC_D2C_Message_Type_Device_Properties to avoid a race condition that cause to types of messages to replace each other.
> Fix issue in reboot/restart flow and race condition in D2C messaging util

- src/agent/adu_core_interface/src/adu_core_interface.c
- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
- src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
- src/utils/d2c_messaging/inc/aduc/d2c_messaging.h
- src/utils/d2c_messaging/src/d2c_messaging.c
Fix issue in reboot/restart flow and race condition in D2C messaging util (#242)
* Fix an issue for image-based update scenario where the device doesn't reboot after the new image is installed.
* Add ADUC_D2C_Message_Type_Device_Properties to avoid a race condition.
> Merge 'develop' into 'main'

- scripts/clang-format.sh
- scripts/githooks/pre-commit.sh
Revert clang-format.sh due to issues with dry-run of staged content on some versions and disable in precommit githook for now due to incompatible sets of cmd-line argument across versions.
> Revert clang-format.sh and disable from precommit git hook

- tools/AduCmdlets/README.md
Modifying README to clarify that the Azure CLI is the recommended approach for using import actions from the command line.
> Added README section for Azure CLI

- src/agent/adu_core_interface/src/adu_core_interface.c
- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
- src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
- src/utils/d2c_messaging/inc/aduc/d2c_messaging.h
- src/utils/d2c_messaging/src/d2c_messaging.c
Fix issue in reboot/restart flow and race condition in D2C messaging util (#242)
- Fix an issue for image-based update scenario where the device doesn't reboot after the new image is installed.
- Add ADUC_D2C_Message_Type_Device_Properties to avoid a race condition.
Note | These changes passed e2e verification internally.
> Merge 'develop' into 'main' (#243)

- src/agent/src/main.c
Removed the logging prompt from the GetConnectionInfoFromEIS() function because it can cause confusion when called by other sections than  main.c. The caller should be the one to inform the user not the function being called.
Related bug: https://microsoft.visualstudio.com/OS/_queries/edit/41718105/?triage=true
> Removed log message for retrieving connection information from AIS 

- docs/agent-reference/how-to-build-agent-code.md
Currently, the agent cannot build without having DO as a dependency. To avoid failures, I think we should make the modification on the documentation
> One line fix on how-to-build-agent-code.md

- src/logging/zlog/CMakeLists.txt
- src/logging/zlog/src/init.c
Use the recursive mkdir helper
> Bug 42608779: ADUC_Logging_Init assumes parent paths exist

- src/agent/src/main.c
Ran valgrind with file descriptor traching:
sudo -u adu $VALGRIND_BIN --track-fds=all /usr/bin/AducIotAgent -l0 -e
Before the fix it leaks the agent zlog init'ed from agent/main.c
After the fix, valgrind shows that it does not leak it.
> fix zlog file handle leak

- src/adu_workflow/src/agent_workflow.c
- src/utils/workflow_utils/src/workflow_utils.c
workflow_transfer_data was not updating the workfolder so processing of replacement workflow (deferred or not) was using the previous workflow's workfolder that was cached in the property cache.  Fix is to set the workfolder with new workflow data upon transfer (which happens right before processing the replacement workflow).
> Update cached workfolder when processing replacement workflow

- src/agent/src/main.c
If any of these goto done is called, ConfigInfo_Unit will call Uninit on an uninitialized ConfigInfo!  
```C
bool GetConnectionInfoFromConnectionString(ADUC_ConnectionInfo* info, const char* connectionString)
{
bool succeeded = false;
if (info == NULL)
{
goto done;
}
if (connectionString == NULL)
{
goto done;
}
memset(info, 0, sizeof(*info));
char certificateString[8192];
if (mallocAndStrcpy_s(&info->connectionString, connectionString) != 0)
{
goto done;
}
info->connType = GetConnTypeFromConnectionString(info->connectionString);
if (info->connType == ADUC_ConnType_NotSet)
{
Log_Error("Connection string is invalid");
goto done;
}
info->authType = ADUC_AuthType_SASToken;
// Optional: The certificate string is needed for Edge Gateway connection.
ADUC_ConfigInfo config;
memset(&config, 0, …
```
> GetConnectionInfoFromConnectionString crashes on failure.

- src/utils/config_utils/tests/main.cpp
- src/utils/eis_utils/tests/main.cpp
- Moved cout to cerr so the catch2 test runner doesn't attempt to create more filters/bugs from the std::cout output
Bug for PR: https://microsoft.visualstudio.com/OS/_queries/edit/42919115/?triage=true
> Moved all unit tests running CATCH2_CONFIG_RUNNER to output to cerr instead of cout so the catch2 test runner isn't confused

- src/utils/c_utils/src/connection_string_utils.c
- Added an input param check for ConnectionStringUtils_IsNestedEdge to prevent unit test error messages
- Bug for PR: https://microsoft.visualstudio.com/OS/_queries/edit/42934385/?triage=true
> Added input params checks to ConnectionStringUtils_IsNestedEdge to prevent test failures

- src/CMakeLists.txt
If inode does not fit into 32-bit offset, then getdirents in glic will return errno 75 EOVERFLOW
It only repros on 32-bit arm running in qemu/docker on top of 64-bit host os.
Compiling with -D_FILE_OFFSET_BITS=64 seems to fix the issue.
> fix readdir EOVERFLOW for qemu arm32 on 64bit host

- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/utils/c_utils/tests/c_utils_ut.cpp
- Free malloc'ed updateName out param from ADUC_ParseUpdateType in swupdate_handler.cpp
- Do the same in c_utils unit tests that call ADUC_ParseUpdateType
```sh
/opt/valgrind.3.19.0/bin/valgrind --leak-check=full ./out/bin/c_utils_unit_tests
```
```
==833634==
==833634== HEAP SUMMARY:
==833634==     in use at exit: 0 bytes in 0 blocks
==833634==   total heap usage: 4,153 allocs, 4,153 frees, 508,776 bytes allocated
==833634==
==833634== All heap blocks were freed -- no leaks are possible
==833634==
==833634== For lists of detected and suppressed errors, rerun with: -s
==833634== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
```
==831838==
==831838== HEAP SUMMARY:
==831838==     in use at exit: 56 bytes in 4 blocks
==831838==   total heap usage: 4,153 allocs, 4,149 …
```
> Fix memleak ADUC_ParseUpdateType

- src/libaducpal/inc/aducpal/unistd.h
- src/libaducpal/src/unistd.c
- src/utils/c_utils/src/string_c_utils.c
Changing LoadBufferWithFileContents to use fopen, fgets, fclose rather than open, read, close?  The latter is a bit quirky on Windows.
> Change LoadBufferWithFileContents to use FILE APIs.

- src/adu_workflow/src/agent_workflow.c
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/CMakeLists.txt
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/tests/CMakeLists.txt
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/tests/microsoft_delta_download_handler_utils_ut.cpp
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/source_update_cache/CMakeLists.txt
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/source_update_cache/src/source_update_cache_utils.c
- src/extensions/step_handlers/apt_handler/CMakeLists.txt
- src/extensions/step_handlers/apt_handler/src/apt_handler.cpp
- src/extensions/step_handlers/apt_handler/tests/CMakeLists.txt
- src/extensions/step_handlers/script_handler/CMakeLists.txt
- src/extensions/step_handlers/script_handler/src/script_handler.cpp
- src/extensions/step_handlers/simulator_handler/CMakeLists.txt
- src/extensions/step_handlers/simulator_handler/src/simulator_handler.cpp
- src/extensions/step_handlers/simulator_handler/tests/CMakeLists.txt
- src/extensions/step_handlers/swupdate_handler/CMakeLists.txt
- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/extensions/step_handlers/swupdate_handler_v2/CMakeLists.txt
- src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
- src/extensions/step_handlers/swupdate_handler_v2/tests/CMakeLists.txt
- src/extensions/update_manifest_handlers/steps_handler/CMakeLists.txt
- src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
- src/platform_layers/simulator_platform_layer/src/simulator_adu_core_impl.cpp
- src/utils/workflow_utils/inc/aduc/workflow_utils.h
- src/utils/workflow_utils/src/workflow_utils.c
- src/utils/workflow_utils/tests/workflow_get_update_file_ut.cpp
- src/utils/workflow_utils/tests/workflow_utils_ut.cpp
workflow_get_update_file and workflow_get_update_file_by_name unnecessarily allocate the FileEntity for the out param. Fixed to just pass in address of stack variable instead to avoid fragmenting the heap.
> No alloc FileEntity from workflow_get_update_file

- src/extensions/component_enumerators/examples/contoso_component_enumerator/CMakeLists.txt
- src/extensions/content_downloaders/curl_downloader/CMakeLists.txt
- src/extensions/content_downloaders/deliveryoptimization_downloader/CMakeLists.txt
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/plugin/CMakeLists.txt
- src/extensions/step_handlers/apt_handler/CMakeLists.txt
- src/extensions/step_handlers/simulator_handler/CMakeLists.txt
- src/extensions/step_handlers/swupdate_handler_v2/CMakeLists.txt
- src/extensions/update_manifest_handlers/steps_handler/CMakeLists.txt
as per [CMake add_library doc](https://cmake.org/cmake/help/latest/command/add_library.html#command:add_library):
`SHARED libraries are linked dynamically and loaded at runtime. MODULE libraries are plugins that are not linked into other targets but may be loaded dynamically at runtime using dlopen-like functionality`
The intention of extensions is to be plugins, not to allow other targets to directly link with them.  This only affects non-windows platforms.
> SHARED -> MODULE to avoid linking to extensions

- scripts/install-deps.sh
To better align DU and DO development, and to resolve 
CMake Error in sdk-cpp/CMakeLists.txt:
Imported target "Boost::filesystem" includes non-existent path
"/include"
in its INTERFACE_INCLUDE_DIRECTORIES.
> Set default DO ref to main

- azurepipelines/build/README.md
Currently says Debian 9 arm32 is a supported pipeline build, but the adu-debian-arm32-build.yml file has the targetOS as Debian 10 - and as far as I am aware this is actually the supported build. Updating to reflect this.
> Update Pipelines Build README.md

- azurepipelines/e2e_test/e2etest.yaml
https://docs.python.org/3/whatsnew/3.11.html#faster-cpython
Last 2 runs using python 3.10:
9812 secs
16346 secs
avg => 13079
Last 2 runs using python 3.11:
8649 secs
10280 secs
avg => 9464.5
13079 / 9464.5  => 1.4x speedup.
> 1.4x perf speedup by using python 3.11 in e2e test pipelines

- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/source_update_cache/CMakeLists.txt
- src/utils/parson_json_utils/CMakeLists.txt
- src/utils/permission_utils/CMakeLists.txt
- src/utils/workflow_data_utils/CMakeLists.txt
Other libraries in this project set POSITION_INDEPENDENT_CODE, ex. workflow_utils, and *depend* on these libraries.
Therefore, they need to be position indepent as well.
Fixes compilation issues seen first in OpenWRT for device update v0.8.0.
> fix: cmake misses some POSITION_INDEPENDENT_CODE settings

- src/agent/command_helper/src/command_helper.c
An hardcoded `"adu"` remained in the code, while the compilation flag `ADUC_FILE_GROUP`
allows the user to define its own group name, which could be different then `"adu"`.
> fix: use ADUC_FILE_GROUP instead of hardcoded "adu"

- scripts/error_code_generator_defs/error_code_defs_generator.py
All other previous usages of `_Bool` were already removed in PR #268.
These seem to be the last two left.
This patch is actually necessary in some compiler scenarios using Musl.
> Remove remaining usages of _Bool from generated error code.

- snap/local/README.md
- snap/snapcraft.yaml
- src/utils/eis_utils/CMakeLists.txt
- src/utils/eis_utils/src/eis_coms.c
[Bug 43844560](https://microsoft.visualstudio.com/OS/_workitems/edit/43844560): Setting euid with Strict Confinement in Snap, for AIS & DU integration
This full AIS integration is blocked by the strict confinement restriction.
Right now this can still work, with detailed documentation, but this is not the appropriate designed communication mechanism between AIS and DU
> Ubuntu Core Snap - AzIoTIdentity integration

- CMakeLists.txt
- docs/agent-reference/how-to-build-deviceupdate-agent-snap.md
- scripts/build.sh
- snap/hooks/configure
- snap/local/README.md
- snap/snapcraft.yaml
- src/utils/eis_utils/CMakeLists.txt
- src/utils/eis_utils/inc/eis_err.h
- src/utils/eis_utils/src/eis_err.c
- src/utils/eis_utils/src/eis_utils.c
> Under Strict Confinement - AzIoTIdentity integration 

- azurepipelines/e2e_test/packer/deltagen/README.md
- azurepipelines/e2e_test/packer/deltagen/deviceupdate-deltagen.pkr.hcl
- azurepipelines/e2e_test/packer/deltagen/scripts/configure-apt-repo.sh
- azurepipelines/e2e_test/packer/deltagen/scripts/generate-delta.sh
- azurepipelines/e2e_test/packer/deltagen/scripts/install-diffgen-tool.sh
- azurepipelines/e2e_test/packer/deltagen/scripts/install-prereqs.sh
- azurepipelines/e2e_test/packer/deltagen/scripts/run.sh
- Add packer hcl to facilitate building docker image for building DeltaUpdate payloads
- Add scripts in scripts dir are run during `packer build .` to get the docker image ready
- Add scripts/run.sh for running the container to build the delta from source/target .swu and priv.pem
> Packer template for DeltaUpdate-Gen docker image and Run Script

- src/utils/system_utils/CMakeLists.txt
- src/utils/system_utils/inc/aduc/system_utils.h
- src/utils/system_utils/src/system_utils.c
- src/utils/system_utils/tests/CMakeLists.txt
- src/utils/system_utils/tests/system_utils_ut.cpp
ado bug: [Bug 43590764](https://microsoft.visualstudio.com/OS/_workitems/edit/43590764): ADUC_SystemUtils_FormatFilePathHelper has incorrect offset
- Add unit tests for with and without trailing slash in dirPath
- Correct to be dirPathSize - 1
> Fix FormatFilePathHelper off by one for trailing fwd slash

- cmake/aduc_security.cmake
- src/utils/crypto_utils/CMakeLists.txt
- src/utils/root_key_utils/CMakeLists.txt
- Add embed_test_root_keys_if_applicable cmake function into new security.cmake
- Invoke embed_test_root_keys_if_applicable instead of unconditionally including test root keys
- Ran cmake-format.sh
- Verified the following using `objdump -s out/src/utils/root_key_utils/CMakeFiles/root_key_utils.dir/src/root_key_lists.c.o`:
- `--type=Debug`  has 2 retail *and 2 test keys*
- `--type=RelWithDebInfo` has only 2 retail keys
-   `--type=Relelease` has only 2 retail keys
-   `--type=MinSizeRel` has only 2 retail keys
> Add cmake fn to add test root keys only for debug builds

- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/src/microsoft_delta_download_handler_utils.c
- src/extensions/extension_manager/inc/aduc/extension_manager_download_options.h
- src/extensions/extension_manager/src/extension_manager.cpp
- src/extensions/extension_manager/src/extension_manager_helper.cpp
- src/extensions/step_handlers/apt_handler/src/apt_handler.cpp
- src/extensions/step_handlers/script_handler/src/script_handler.cpp
- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
- src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
[Bug 42998192](https://microsoft.visualstudio.com/OS/_workitems/edit/42998192): Why isn't Default_ExtensionManager_Download_Options extern in extension_manager.hpp ?
> Move extern Default_ExtensionManager_Download_Options into header

- src/communication_managers/iothub_communication_manager/CMakeLists.txt
- src/communication_managers/iothub_communication_manager/src/iothub_communication_manager.c
Hi iot-hub-device-update Team,
Regarding issue 
https://github.com/Azure/iot-hub-device-update/issues/367 
and 
https://github.com/Azure/iot-hub-device-update/issues/212
i added a new handling for the communication handler in case of "unauthenticated " state with reason "no network".
I saw on multiple logs on my side that in case "no network" the module twin is empty for the reported properties items.
That could happen if the identity service re-provision the device. This PR should fix that behaviour.
new handling:
1) try to restart agent to prevent empty reported properties in module twin  
2) if restart agent could not be performed, wait for at least 5 minutes to retry.
> added handling to restart adu in case of "unauthenticated:no network"

- scripts/install-deps.sh
Because DO has not created the latest tag, to adopt the change we will use `develop` branch, and then update it to v1.0.2 once DO creates the new tag. 
Quoted from Shishir:  the fixes are only in develop currently and I would like to avoid cherry-picking non-trivial changes. Can you point to our develop branch instead? If not, I will see when we can merge into main and create a tag.
If we like it to point to v1.0.2 instead, we can ask Shishir help create a tag new
> Fix Bug: Remove mandatory PLATFORM parameter for DO bootstrap script and DU install-deps

- scripts/install-du.ps1
Otherwise, calling ./scripts/install-du.ps1 -Type Debug -Package results in:
```ps
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Redist\MSVC\14.34.31931\debug_nonredist\x64\Microsoft.VC143.DebugCRT\msvcp140d.dll is not a file or directory doesn't exist                                                                                                                                                                
At C:\src\iot-hub-device-update\scripts\install-du.ps1:59 char:9                                                                                                             
+         throw "$Source is not a file or doesn't exist"                                                                                                                     
+ …
```
> buildtools 14.34.31931 -> 14.36.32532 to fix new enlistment.

- docs/agent-reference/how-to-build-agent-code.md
Addressing ihttps://github.com/Azure/iot-hub-device-update/issues/500 - docs/agent-reference/how-to-build-agent-code.md contains text referencing deleted content
We will add more document and link back when it's ready.
> Fix broken link in how-to-build-agent-code.md

- snap/snapcraft.yaml
add DO as stage-snaps, so that it is one of the snap dependency
add allow-auto-connection: true for DO and AIS, so that it won't need the manual connection. and add allow-auto-connection  for account-control because he account-control interface in Snap provides an application with the ability to create, delete, and manage user accounts on a system.
> Small fix on snap yaml for publishing to Ubuntu Core Store

- azurepipelines/build/native/adu-windows-msvc2022-amd64-build.yml
- scripts/build.ps1
- scripts/install-deps.ps1
- scripts/run_uts.ps1
- src/utils/system_utils/tests/system_utils_ut.cpp
- Uses Microsoft-Hosted vmImage
- Triggered by feature branch for now (will be triggered by develop too once merged there)
- Builds and runs unit tests
- Publish test results
- Publish bin and lib artifacts (including .PDB symbols)
> Add Windows Build Pipeline

- azurepipelines/build/native/adu-windows-msvc2022-amd64-build.yml
- scripts/build.ps1
- Add steps to cross-compile ARM64 and generate 2 additional ARM64 build artifacts
- Address comments from the previous PR
> Add ARM64 Cross-Compilation to Windows Build Pipeline

- scripts/install-deps.sh
Building catch2 from sources fails on `#pragma GCC diagnostic ignored "-Wcomma-subscript"` due to using gcc-9 and g++-9 packages on Ubuntu 20.04
This change installs gcc-10 and g++-10 packages on Ubuntu 20.04 to resolve this and also exports CC and CXX env variables so that catch2 CMake build will use gcc-10 and g++-10 instead of gcc-9 and g++-9.
> Fix installs-deps -a catch2 issue on ubuntu 20.04

- azurepipelines/e2e_test/e2etest.yaml
- azurepipelines/e2e_test/templates/e2e_test_vm_cleanup.yaml
- azurepipelines/e2e_test/templates/e2e_vm_setup.yaml
- azurepipelines/e2e_test/terraform/host/DeviceUpdateHost.tf
This addresses the following intermittent errors in "Creating the virtual machines" in E2E test runs that produce:
```
azurerm_linux_virtual_machine.deviceupdatevm (remote-exec): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
azurerm_linux_virtual_machine.deviceupdatevm (remote-exec): E: Unable to lock directory /var/lib/apt/lists/
```
> Wait for any apt or apt-get process to finish before doing apt update during TF vm creation

- tools/packer/README.md
- tools/packer/build/README.md
- tools/packer/build/duagent-build.pkr.hcl
- tools/packer/build/scripts/README.md
- Add packer HCL to do build docker image with cross-compiled build of DU agent in Debian11 ARM64
- Add README.md on how to run packer, docker container, and get build artifacts off of container
Addresses github issue: https://github.com/Azure/iot-hub-device-update/issues/484
> Packer for Deb11 ARM64 docker image containing DU Agent build artifacts

- CMakeLists.txt
- src/extensions/step_handlers/apt_handler/tests/CMakeLists.txt
- src/extensions/step_handlers/simulator_handler/CMakeLists.txt
- src/extensions/step_handlers/simulator_handler/src/simulator_handler.cpp
- src/utils/installed_criteria_utils/tests/CMakeLists.txt
- Added in to remove the dependency on hard coded /tmp directories in some parts of the code base
> Add the compile time configuration location for the /tmp directory for portability

- src/utils/config_utils/inc/aduc/config_utils.h
- src/utils/config_utils/src/config_utils.c
- src/utils/config_utils/tests/CMakeLists.txt
- src/utils/config_utils/tests/config_utils_ut.cpp
- src/utils/parson_json_utils/inc/parson_json_utils.h
- src/utils/parson_json_utils/src/parson_json_utils.c
These changes are essential modifications to facilitate device registration through the Device Provisioning Service (via MQTT) and to communicate with the MQTT broker.
- Introduced connection types: `"ADPS2"` and `"MQTTBroker"`
- For the "ADPS2" type, connection details can be found at **"agents[###].connectionData.dps"**
- For the "MQTTBroker" type, connection details are located under **"agents[###].connectionData.mqttBroker"**.**
See [Using the MQTT protocol directly (as a device)](https://learn.microsoft.com/en-us/azure/iot/iot-mqtt-connect-to-iot-dps#using-the-mqtt-protocol-directly-as-a-device) and [Overview of the MQTT Support in Azure Event Grid (Preview)](https://learn.microsoft.com/en-us/azure/event-grid/mqtt-overview) for more details.
> Adding DPS and MQTTBroker configurations support in du-config.json

- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- calls now the correct revert action in the adu-swupdate.sh script
> fix CancelApply swupdate_handler_v1

- src/adu-shell/src/main.cpp
- src/agent/command_helper/src/command_helper.c
- src/agent/src/main.c
- src/extensions/content_downloaders/curl_downloader/curl_content_downloader.cpp
- src/extensions/content_downloaders/deliveryoptimization_downloader/deliveryoptimization_content_downloader.EXPORTS.cpp
- src/extensions/content_downloaders/deliveryoptimization_downloader/deliveryoptimization_content_downloader.cpp
- src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/plugin/src/microsoft_delta_download_handler_plugin.EXPORTS.c
- src/extensions/step_handlers/apt_handler/src/apt_handler.cpp
- src/extensions/step_handlers/apt_handler/src/apt_parser.cpp
- src/extensions/step_handlers/script_handler/src/script_handler.cpp
- src/extensions/step_handlers/simulator_handler/src/simulator_handler.cpp
- src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
- src/extensions/step_handlers/swupdate_handler_v2/src/handler_create.cpp
- src/extensions/step_handlers/wim_handler/src/wim_handler_1.cpp
- src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
- src/inc/aduc/aduc_banned.h
- src/utils/c_utils/CMakeLists.txt
- src/utils/c_utils/inc/aduc/string_c_utils.h
- src/utils/c_utils/src/string_c_utils.c
- src/utils/c_utils/tests/c_utils_ut.cpp
- src/utils/jws_utils/src/jws_utils.c
- src/utils/permission_utils/tests/permission_utils_ut.cpp
- src/utils/system_utils/src/system_utils.c
- Add aduc_banned.h to strategic executable and module cmake targets' .c/.cpp (cannot add to .h without lots of refactoring to avoid it messing up system headers)
- Make use of strncpy in some impl files result in compiler error
- Replace instances of strncpy with ADUC_Safe_StrCopyN
- Add unit tests for ADUC_Safe_StrCopyN
- Remove unused ReadDelimitedValueFromFile function and tests
Attempting to use strncpy now will result in compilation error that looks like this:
```sh
user/jw-msft/merge-develop-into-rootkey-feature-2023_10_03
/home/jw/src/iot-hub-device-update/src/utils/jws_utils/src/jws_utils.c: In function ‘ExtractJWSSections’:
/home/jw/src/iot-hub-device-update/src/inc/aduc/aduc_banned.h:16:55: error: ‘strncpy_is_banned__Please_use_ADUC_Safe_StrCopyN_instead’ undeclared (first use …
```
> Ban strncpy with compilation error, replaced by ADUC_Safe_StrCopyN

- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/CMakeLists.txt
- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/inc/aduc/agent_module_interface_internal.h
- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_agent_info_management.c
- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_agent_info_management_internal.c
- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_enrollment_management.c
- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_enrollment_management_internal.c
A wholesale copy of per-operation internal interface impls declared in [agent_module_interface_internal.h](https://github.com/Azure/iot-hub-device-update/compare/topic/v2-pr-fb...user/jw-msft/v2-internalmgmt?expand=1#diff-83350046f6ab4ac3afc6988cc6917424e53b8dd28719445692eb92aeafa86234) from `adu_<operation>_management.c` into respective `adu_<operation>_management_internal.c`
> Factor out req-resp internal mgmt impls

- src/utils/workflow_utils/src/workflow_utils.c
Repro information and log output in bug here: https://microsoft.visualstudio.com/OS/_workitems/edit/48256773
> Added exit handler to ensure no double free in workflow_get_workfolder when parent workfolder is used

- src/extensions/agent_modules/cloud_communication/adps2_mqtt_client/src/adps2_mqtt_client_module.c
- src/extensions/agent_modules/cloud_communication/communication_channel/mqtt_broker/src/adu_communication_channel.c
- src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_mqtt_client_module.c
- src/extensions/agent_modules/shared/upd_utils/src/adu_upd_utils.c
- Remove hard-coded clientId for mqtt EG broker connections
- Use state store external deviceId for clientId when connecting to mqtt broker
- Continue using initData->sessionId for DPS mqtt connection
- Fix type issue in AduUpdUtils_TransitionState
> Allow multiple agents to connect to a broker

- azurepipelines/build/native/adu-ubuntu-amd64-build.yml
- azurepipelines/build/native/adu-ubuntu-arm64-build.yml
- azurepipelines/build/templates/adu-native-build-steps.yml
- scripts/build.sh
- scripts/docker/templates/Dockerfile.template
- scripts/install-deps.sh
- Fixed native build pipeline issues
- Removed reliance on docker
- Changed dependency installation flow to prep for cache flows.
> Re-Enabling native build pipelines for Ubuntu 20.04 and Ubuntu 22.04

- azurepipelines/build/native/adu-windows-msvc2022-amd64-build.yml
- azurepipelines/e2e_test/templates/e2e_test_run.yaml
- azurepipelines/e2e_test/templates/e2e_vm_setup.yaml
- scripts/build.sh
- scripts/install-deps.sh
- Adds the PipAuthenticate@1 function for the checkout of the PIP artifacts to be used for various builds. 
- Removed unnecessary dependence on python2.7 which can cause flags
- Updated error warnings in install-deps.sh and install-deps.ps1 to use PipAuthenticate when working in pipelines or creating release artifacts
> Adding pip authenticate to pipelines

- src/diagnostics_component/utils/file_info_utils/src/file_info_utils.c
Fix an issue in the `FileInfoUtils_FillFileInfoWithNewestFilesInDir()` function where, if an error occurs after the `FileInfo` structure has been partially populated, the cleanup code incorrectly handles the `fileName` fields. Specifically, the cleanup code frees the fileName fields but does not properly reset these fields in the input array.
> Fix potential double free issue in FileInfoUtils_FillFileInfoWithNewestFilesInDir

- src/utils/extension_utils/src/extension_utils.c
STRING_construct_sprintf() is erroneously called with format specifier "%d" for fileSize being a "long long [int]". Depending on the architecture this can lead to subsequent arguments getting misinterpreted during vsnprintf() invocation in this function. Found that bug on arm32 architecture (i.MX6).
> Fix extension_utils.c: json file generation in Register[Handler]Extension
