Azure/iot-hub-device-update

docs/agent-reference/how-to-build-agent-code.md

Added build instructions for building the agent to provision with the IoT Identity Service

Added build instructions for building the agent to provision with the IoT Identity Service

---

tools/AduCmdlets/README-PowerShell.md
tools/AduCmdlets/README-bash.md
tools/AduCmdlets/create-adu-import-manifest.sh

Bug 32485748: Create bash script to generate import manifest (parity with AduUpdate.psm1)
bash version of the PowerShell script.
Bonus: Split README to PowerShell and bash versions.
Bonus: Fixed up some stuff in the PowerShell README

Adu update bash script

---

azurepipelines/adu-ubuntu-arm64-build.yml

- Fixed and checked the fix within the arm64 pipeline. 
- Also checked with the python yaml check Jeff provided

Fixed and checked file padding

---

src/adu-shell/src/main.cpp
src/agent/src/main.c

Expected value for ADUC LOG LEVEL: 0-3
So the >= should be changed to >

Bug 32763332: LogLevel should include LOG_ERROR in main.c

---

azurepipelines/adu-debian-arm32-build.yml
azurepipelines/adu-ubuntu-amd64-build.yml
azurepipelines/adu-ubuntu-arm64-build.yml

- Removed scripts and tools directories from the build pipeline exemption

Bug 32910784: Changing scripts should kick off a pipeline build, 

---

scripts/install-deps.sh

- Required to include C-SDK fixes in our iot-c-sdk dependency

Advanced c-sdk version from LTS_01_2021 to master 

---

CMakeLists.txt
azurepipelines/adu-debian-arm32-build.yml
azurepipelines/adu-ubuntu-amd64-build.yml
azurepipelines/adu-ubuntu-arm64-build.yml

Updated agent version to remove rc1

---

src/extensions/component-enumerators/examples/contoso-component-enumerator/demo/sample-updates/CreateSampleMSOEUpdate-8.x.ps1
src/extensions/component-enumerators/examples/contoso-component-enumerator/demo/sample-updates/data-files/camera-firmware-3.0.json
src/extensions/component-enumerators/examples/contoso-component-enumerator/demo/sample-updates/data-files/motor-firmware-3.1.json

- Fix an error sample MSE update 8.0 due to invalid components selector.
- Fix incorrect version number in some firmware version file.

Fix typos and remove steps in MSOE example update 8.0

---

src/content_handlers/apt_handler/src/apt_handler.cpp
src/content_handlers/swupdate_handler/src/swupdate_handler.cpp
src/utils/workflow_utils/src/workflow_utils.c

CP'ed from internal development branch.

Fix regression in reboot and restart logics in APT handler and SWUpdate handler (v1)

---

azurepipelines/build/docker/adu-debian-arm32-build.yml
azurepipelines/build/docker/adu-ubuntu-amd64-build.yml
azurepipelines/build/docker/adu-ubuntu-arm64-build.yml
src/content_handlers/apt_handler/src/apt_handler.cpp
src/content_handlers/swupdate_handler/src/swupdate_handler.cpp
src/utils/workflow_utils/src/workflow_utils.c

- Fix regression in reboot and restart logics in APT handler and SWUpdate handler (v1) (#187)
- The fix has been tested and cherry-pick'ed from internal development branch.

Release 0.8.2 - hot fix for reboot and restart logics regression

---

azurepipelines/build/docker/adu-debian-amd64-build.yml
azurepipelines/build/docker/adu-debian-arm64-build.yml
docker/arm32/Dockerfile
docker/arm64/Dockerfile

Cherry-Pick from https://github.com/Azure/adu-private-preview/pull/523
- Enable support for Debian 10 amd64
- Fix supply chain warnings

Support OS Debian 10 amd64

---

tools/AduCmdlets/AduImportUpdate.psm1

makes same change which was created here: https://github.com/Azure/iot-hub-device-update/pull/215/files

fix where updateIdStr gets created

---

docs/agent-reference/update-manifest-v4-schema.md

**Changes**
- Fix broken link
- Minor text changes

Update Update-Manifest markdown

---

scripts/install-deps.sh

- Added cleanup steps for tarballs, old folders, etc
- Added cleanup for the /adu/testdata/ folder
Associated bugs:
- DO bootstrap cleanup bug (GSL, gtest folders) https://microsoft.visualstudio.com/OS/_workitems/edit/42633683/?triage=true
- Bug for this PR: https://microsoft.visualstudio.com/OS/_workitems/edit/42634183

Changed install-deps to clean up after itself

---

src/utils/installed_criteria_utils/inc/aduc/installed_criteria_utils.hpp
src/utils/installed_criteria_utils/src/installed_criteria_utils.cpp
src/utils/installed_criteria_utils/tests/installed_criteria_utils_ut.cpp

Fix for the UT.  Fixes the scoping issue in RemoveInstaslledCriteria and ""  passed via RemoveAllInstalledCriteria().  Might be good to pick this (change the ADUCPAL_ call back) to develop.

Fix installed_criteria_utils.

---

src/utils/d2c_messaging/tests/d2c_messaging_ut.cpp

Cherry Pick changes from wiot-s1 branch

Mark test case "30 retries - httpStatus 401" as functional - takes 30s to run

---

src/agent/src/main.c

Cherry-pick of this commit in feature/wiot-s1 branch: https://github.com/Azure/iot-hub-device-update/commit/e6754f3fdbcadf098a15811b16aac0aceda723f6
Original PR: https://github.com/Azure/iot-hub-device-update/pull/324

Cherry-pick from wiot-s1 feature branch: GetConnectionInfoFromConnectionString crashes on failure. (#324)

---

src/agent/CMakeLists.txt
src/agent/command_helper/src/command_helper.c
src/agent/src/main.c
src/libaducpal/inc/aducpal/sys_stat.h
src/libaducpal/src/sys_stat.c

Remove command helper in WIOT

---

snap/README.md

Readme Design Doc for Snapcraft (Ubuntu Core Support)

---

src/extensions/step_handlers/script_handler/src/script_handler.cpp
src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
src/extensions/step_handlers/swupdate_handler_v2/tests/testdata/adu-yocto-ab-rootfs-update/create-yocto-ab-rootfs-update-import-manifest-1.0.ps1
src/extensions/step_handlers/swupdate_handler_v2/tests/testdata/adu-yocto-ab-rootfs-update/payloads/example-a-b-update.sh
src/extensions/step_handlers/swupdate_handler_v2/tests/testdata/swupdate_filecopy/example-du-swupdate-script.sh

- Fix bug in the SWUpdate Handler V2 example scripts
- Fix some typos in SWUpdate Handler V2 and Script Hanlder

Fix bug in swupdate-handler v2 example

---

cmake/agentRules.cmake
cmake/automate-vcpkg.cmake
scripts/build.ps1
scripts/install-deps.ps1
src/extensions/CMakeLists.txt
src/extensions/content_downloaders/CMakeLists.txt
src/extensions/content_downloaders/deliveryoptimization_downloader/deliveryoptimization_content_downloader.EXPORTS.cpp
src/extensions/step_handlers/CMakeLists.txt
src/extensions/step_handlers/wiot_handler/CMakeLists.txt
src/extensions/step_handlers/wiot_handler/README.md
src/extensions/step_handlers/wiot_handler/inc/step_handler.hpp
src/extensions/step_handlers/wiot_handler/inc/wiot_handler_1.hpp
src/extensions/step_handlers/wiot_handler/src/aducresult.hpp
src/extensions/step_handlers/wiot_handler/src/handler_create.cpp
src/extensions/step_handlers/wiot_handler/src/step_handler.cpp
src/extensions/step_handlers/wiot_handler/src/wiot_handler_1.cpp
src/extensions/step_handlers/wiot_handler/src/workflow_ptr.hpp
src/libaducpal/src/unistd.c
src/utils/c_utils/src/string_c_utils.c

Includes:
* WIoT handler (currently "microsoft/wiot:1")
* DO downloader.  (Turns out the DO wrapper made this straight forward.  I started down the path of writing a Windows COM based downloader!)

WIoT: handler and DO downloader

---

src/extensions/step_handlers/wiot_handler/CMakeLists.txt
src/extensions/step_handlers/wiot_handler/src/step_handler.cpp
src/extensions/step_handlers/wiot_handler/src/wiot_handler_1.cpp

Installs audacity (to `$env:LocalAppData/Programs/audacity`), creates a portable settings folder with a default audacity.cfg file (disabling updates) and creates a shell folder shortcut.

WIoT demo handler code

---

src/extensions/step_handlers/swupdate_handler_v2/inc/aduc/swupdate_handler_v2.hpp
src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp

during implementation iot-hub-device-update 1.0.1 and testing swupdate handler v2 i found some possible mistakes during integration the swupdate handler v2. Here are my improvements.

Use custom script in CancelApply and Apply step

---

src/adu_workflow/src/agent_workflow.c
src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/CMakeLists.txt
src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/tests/CMakeLists.txt
src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/handler/utils/tests/microsoft_delta_download_handler_utils_ut.cpp
src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/source_update_cache/CMakeLists.txt
src/extensions/download_handlers/plugin_examples/microsoft_delta_download_handler/source_update_cache/src/source_update_cache_utils.c
src/extensions/step_handlers/apt_handler/CMakeLists.txt
src/extensions/step_handlers/apt_handler/src/apt_handler.cpp
src/extensions/step_handlers/apt_handler/tests/CMakeLists.txt
src/extensions/step_handlers/script_handler/CMakeLists.txt
src/extensions/step_handlers/script_handler/src/script_handler.cpp
src/extensions/step_handlers/simulator_handler/CMakeLists.txt
src/extensions/step_handlers/simulator_handler/src/simulator_handler.cpp
src/extensions/step_handlers/simulator_handler/tests/CMakeLists.txt
src/extensions/step_handlers/swupdate_handler/CMakeLists.txt
src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp
src/extensions/step_handlers/swupdate_handler_v2/CMakeLists.txt
src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
src/extensions/step_handlers/swupdate_handler_v2/tests/CMakeLists.txt
src/extensions/step_handlers/wiot_handler/CMakeLists.txt
src/extensions/step_handlers/wiot_handler/src/wiot_handler_1.cpp
src/extensions/step_handlers/wiot_handler/src/workflow_ptr.hpp
src/extensions/update_manifest_handlers/steps_handler/CMakeLists.txt
src/extensions/update_manifest_handlers/steps_handler/src/steps_handler.cpp
src/platform_layers/simulator_platform_layer/src/simulator_adu_core_impl.cpp
src/utils/workflow_utils/inc/aduc/workflow_utils.h
src/utils/workflow_utils/src/workflow_utils.c
src/utils/workflow_utils/tests/workflow_get_update_file_ut.cpp
src/utils/workflow_utils/tests/workflow_utils_ut.cpp

* no alloc of FileEntity from workflow_get_update_file
* remove workflow_free_file_entity and nonalloc out for workflow_get_step_detached_manifest_file

No alloc FileEntity from workflow_get_update_file (#353)

---

src/agent/src/main.c
src/communication_managers/iothub_communication_manager/inc/aduc/iothub_communication_manager.h
src/communication_managers/iothub_communication_manager/src/iothub_communication_manager.c

Moved IoTHub_DeInit() call into IoTHub_CommunicationManager_DeInit() and only call if the IoTHub_Init() has been called.

Improve IoTHub_CommunicationManager_Init and DeInit

---

src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp

- Added clarification for the swupdate trace as per bug: https://microsoft.visualstudio.com/OS/_queries/edit/43011595/?triage=true

Changed updateType telemetry parsing to match tracing

---

src/communication_managers/iothub_communication_manager/src/iothub_communication_manager.c

during implementation iot-hub-device-update 1.0.1, the code won't compile successfully with my gcc compiler version 11.

handle missing use case  IOTHUB_CLIENT_CONNECTION_QUOTA_EXCEEDED

---

src/utils/config_utils/tests/main.cpp
src/utils/eis_utils/tests/main.cpp

git cherry-pick 3f2ffc9dbfbacaf38fd1b346e26f62c335900006
https://github.com/Azure/iot-hub-device-update/commit/3f2ffc9dbfbacaf38fd1b346e26f62c335900006

Cherry-pick wiot-s1 fix for Catch session failed, err=1

---

.cmake-format.json

Also change hwrap to be less aggressive (2 to 6).

Use updated JSON schema. 

---

src/utils/jws_utils/src/jws_utils.c

https://github.com/Azure/iot-hub-device-update/issues/406

Null-terminate jws strncpy

---

src/agent/pnp_helper/CMakeLists.txt
src/agent/pnp_helper/src/pnp_protocol.c

ADO [Bug 43488667](https://microsoft.visualstudio.com/OS/_workitems/edit/43488667): pnp_protocol.c calls LogError -- this should be Log_Error

Chg xlog LogError to aduc logging Log_Error in pnp_protocol

---

CMakeLists.txt
daemon/CMakeLists.txt

- Removed unused CMake command
- Bug for change: https://microsoft.visualstudio.com/OS/_queries/query/1242b094-7c30-4e59-b4fd-0457ce3ae1be/

Removed home folder

---

azurepipelines/e2e_test/README.md
azurepipelines/e2e_test/e2etest.yaml
azurepipelines/e2e_test/scenarios/debian-10-amd64/vm_setup/setup.sh
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/Bundle-update.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/Multi-Component-Update.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/add_device_to_adu_group.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/apt_deployment.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/delete_device.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/diagnostics.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/scenario_definitions.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/self_upgrade.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/vm_setup/devicesetup.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/vm_setup/setup.sh
azurepipelines/e2e_test/scenarios/ubuntu-18.04-arm64/vm_setup/setup.sh
azurepipelines/e2e_test/scenarios/ubuntu-20.04-amd64/vm_setup/setup.sh
azurepipelines/e2e_test/templates/e2e_vm_setup.yaml
scripts/docker/build_docker_image.sh
scripts/install-deps.sh
tools/selfhost/bootstrap.py

Work for Tasks: 
- https://microsoft.visualstudio.com/OS/_queries/edit/44081906/?triage=true
- https://microsoft.visualstudio.com/OS/_queries/edit/44082136/?triage=true

Added AIS provisioning of a module to the e2e flow and tested integration

---

azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/Bundle-update.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/Multi-Component-Update.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/add_device_to_adu_group.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/apt_deployment.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/delete_device.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/diagnostics.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/self_upgrade.py
azurepipelines/e2e_test/scenarios/ubuntu-18.04-amd64/vm_setup/devicesetup.py

Changes dependency includes in the python scripts to allow end-to-end pipeline to run

---

src/extensions/step_handlers/wim_handler/CMakeLists.txt
src/extensions/step_handlers/wim_handler/inc/format_drive.hpp
src/extensions/step_handlers/wim_handler/src/format_drive.cpp
src/extensions/step_handlers/wim_handler/src/wim_step_handler.cpp

[Bug 44356009](https://microsoft.visualstudio.com/OS/_workitems/edit/44356009): [WinIoT] WIM ContentHandler needs to check Volume Label before formatting drive

winiot - Check volume label before format drive

---

src/utils/process_utils/src/process_utils.cpp

fix LoadBufferWithFileContents read to count strBuffSize - 1

---

src/adu_workflow/src/agent_workflow.c
src/extensions/agent_modules/cloud_communication/adps2_mqtt_client/src/adps2_mqtt_client_module.c
src/extensions/agent_modules/cloud_communication/communication_channel/mqtt_broker/src/adu_communication_channel.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/inc/aduc/topic_mgmt_lifecycle.h
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_agent_info_management.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_enrollment_management.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_mqtt_client_module.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/agentinfo_request_operation.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/enrollment_request_operation.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/topic_mgmt_lifecycle.c
src/extensions/agent_modules/cloud_communication/iothub_client/adu_core_interface/src/adu_core_interface.c
src/extensions/agent_modules/device_update_workflow/module/src/device_update_workflow_module.c
src/utils/c_utils/inc/aduc/c_utils.h
src/utils/config_utils/src/config_utils.c
src/utils/config_utils/tests/config_utils_ut.cpp
src/utils/workflow_utils/src/workflow_utils.c

- [rmv ADUC_ALLOC macro](https://github.com/Azure/iot-hub-device-update/commit/6d91e477d8bc22cb954d023de8f69f95c9b02723)
- [rmv ADUC_ALLOC_BLOCK macro](https://github.com/Azure/iot-hub-device-update/commit/c2c507978860bc45d714696075a856e2f37b0bbf)
- Add TopicMgmtLifecycle_UninitRetriableOperationContext
- Add CreateCommunicationMgrState and DestroyCommunicationMgrState

Remove ADUC_ALLOC macros

---

src/extensions/agent_modules/cloud_communication/adps2_mqtt_client/src/adps2_mqtt_client_module.c
src/extensions/agent_modules/cloud_communication/adps2_mqtt_client/src/adps_gen2.c
src/extensions/agent_modules/cloud_communication/communication_channel/mqtt_broker/src/adu_communication_channel.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/agentinfo_request_operation.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/enrollment_request_operation.c
src/utils/config_utils/src/config_utils.c

- [shorten some adps gen2 log strings](https://github.com/Azure/iot-hub-device-update/commit/5ab94306e2a3ce37e169ee4c3547ca20b6cbd3fd)
- [shorten cloud comm log trace strings](https://github.com/Azure/iot-hub-device-update/commit/c16be6cb2e3a53fdf887d0523be41319f9cc0e63)

Shorten cloud comms log trace strings

---

src/extensions/agent_modules/cloud_communication/communication_channel/mqtt_broker/src/adu_communication_channel.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_processupdate.cpp
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_update_management.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/upd_request_operation.c
src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/tests/testdata/adu-mqtt-client-module-test-data/du-config.json
src/extensions/agent_modules/shared/upd_utils/inc/aduc/adu_upd_utils.h
src/extensions/agent_modules/shared/upd_utils/src/adu_upd_utils.c
src/utils/parson_json_utils/src/parson_json_utils.c
src/utils/retry_utils/inc/aduc/retry_utils.h
src/utils/retry_utils/src/retry_utils.c

- [fix idlewait interval, jitter and reconnect wait](https://github.com/Azure/iot-hub-device-update/commit/4d94bd3a3a8dde3d5bf0864f6de1e937334bd3e7)

fix idlewait interval, jitter and reconnect wait

---

src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/agentinfo_request_operation.c
src/extensions/agent_modules/cloud_communication/iothub_client/adu_core_interface/src/startup_msg_helper.c
src/utils/config_utils/inc/aduc/config_utils.h
src/utils/config_utils/src/config_utils.c
src/utils/config_utils/tests/config_utils_ut.cpp

- Remove compatPropertyNames
- Add compatProperties JSON_Value* to config info
- Send compatProperties json verbatim fr cfg in ainfo_req mqtt msg

Use compatProperties from config file

---

src/extensions/agent_modules/cloud_communication/eg_mqtt_broker_client/src/adu_integration.cpp
src/utils/workflow_utils/src/workflow_utils.c
src/utils/workflow_utils/tests/workflow_utils_ut.cpp

- Change upd_resp payload parsing to use "workflowId" at top-level instead of workflow.id
- Remove workflow.action that no longer exists
- Update workflow util UTs

use workflowId top-level prop in upd_resp

---

src/extensions/step_handlers/swupdate_handler_v2/README.md

Fix link to example swupdate v2 link to include /payloads/ and remove -2.1 suffix on filename

Fixes link to example swupdate v2 link

---

azurepipelines/e2e_test/e2etest.yaml
azurepipelines/e2e_test/scenarios/test_runner/apt_deployment.py
azurepipelines/e2e_test/scenarios/test_runner/scenario_definitions.py
azurepipelines/e2e_test/scenarios/testingtoolkit/_adu_test_toolkit.py
azurepipelines/e2e_test/scripts/start_and_check_deployment.sh
azurepipelines/e2e_test/templates/az_vm.template.json

- Removes utilization of terraform and Python code segments. Code is kept for austerity. Can be removed if not useful
- Adds Azure VM template for creating the right image
- Adds Azure CLI for initiating and checking a deployment with Azure CLI commands

Fixes issues with E2E deployments 
